name: GO CI/CD
on:
  push:
    branches: ["main"]
    paths:
      - "clients/**"
      - "events/**"
      - "payments/**"
  workflow_dispatch:
    inputs:
      golang_project:
        description: "Select the Go project to run the workflow on"
        required: true
        type: choice
        options:
          - "clients"
          - "events"
          - "payments"
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Detect which folder changed
      - name: Set project folder
        id: set-dir
        run: |
          if git diff --name-only ${{ github.sha }} ${{ github.sha }}^ | grep -q "^folder-one/"; then
            echo "PROJECT_DIR=folder-one" >> $GITHUB_ENV
            echo "IMAGE_NAME=myuser/folder-one-app" >> $GITHUB_ENV
          elif git diff --name-only ${{ github.sha }} ${{ github.sha }}^ | grep -q "^folder-two/"; then
            echo "PROJECT_DIR=folder-two" >> $GITHUB_ENV
            echo "IMAGE_NAME=myuser/folder-two-app" >> $GITHUB_ENV
          elif git diff --name-only ${{ github.sha }} ${{ github.sha }}^ | grep -q "^folder-three/"; then
            echo "PROJECT_DIR=folder-three" >> $GITHUB_ENV
            echo "IMAGE_NAME=myuser/folder-three-app" >> $GITHUB_ENV
          else
            echo "No relevant changes"
            exit 0
          fi

      # Step 2: Setup Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('${{ github.event.inputs.golang_project }}/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod download
        working-directory: ${{ github.event.inputs.golang_project }}

      # Step 4: Lint
      - name: Run lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ${{ github.event.inputs.golang_project }}

      # Step 5: Run tests
      - name: Run tests
        run: go test ./... -v -coverprofile=coverage.out
        working-directory: ${{ github.event.inputs.golang_project }}

      # Step 6: Build binary
      - name: Build app
        run: go build -o app .
        working-directory: ${{ github.event.inputs.golang_project }}

      # Step 7: Upload artifact
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: go-app
          path: ${{ github.event.inputs.golang_project }}/app
